SolaxToPVOutput:
  logLevel: "WARNING"
  pollIntervalSeconds: 300
  logFile: "solaxtopvoutput.log"

SolaxCloud:
  apiUrl: "https://global.solaxcloud.com"
  tokenId: "set-this-in-config-or-env"
  registrationNr: "set-this-in-config-or-env"

PVOutput:
  systemid: 123456
  apikey: "set-this-in-config-or-env"

SunWindow:
  enabled: true
  latitude: 52.1326
  longitude: 5.2913
  timezone: "Europe/Amsterdam"
  startEvent: "sunrise" #or Dawn
  endEvent: "sunset" # or Dusk
